[versions]
kotest = "6.1.2"
kotlin-gradle-plugin = "2.3.0"
kotlin-logging = "7.0.14"
kotlinx-html = "0.12.0"
ktor = "3.4.0"
ktlint = "1.8.0"
ktlint-gradle-plugin = "14.0.1"
logback = "1.5.26"
logstash-logback-encoder = "9.0"
playwright = "1.58.0"

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit6 = { module = "io.kotest:kotest-runner-junit6", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinx-html" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlint-gradle-plugin" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback-encoder" }
playwright = { module = "com.microsoft.playwright:playwright", version.ref = "playwright" }

[plugins]
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
